name: modern-cmake

channels:
  - conda-forge
  - defaults

dependencies:
  - cmake
  - cpputest
  - spdlog
  - cppcheck
  - make
  - doxygen
  - plantuml
  - python
  - pip
  - pip:
    - -r requirements.txt
